export const Colors = {
  primary: '#9747FF',
  primaryDark: '#7B2FE0',
  primaryLight: '#E8D5F5',
  primaryMid: '#C49BFF',
  accent: '#FF47C7',
  accentLight: '#FFD6F5',
  success: '#4BFFC8',
  successDark: '#00C896',
  warning: '#FFB347',
  error: '#FF4747',
  text: '#1A1A1A',
  textMuted: '#888888',
  textLight: '#BBBBBB',
  white: '#FFFFFF',
  background: '#FAFAFA',
  card: '#FFFFFF',
  border: '#E8E8E8',
  gradientStart: '#F0E6FF',
  gradientMid: '#FFE6F8',
  gradientEnd: '#FFFFFF',
  overlayDark: 'rgba(0,0,0,0.5)',
  // Milestone colours matching Figma
  milestoneGrey: '#E8E0F0',
  milestonePurple: '#9747FF',
  milestoneCyan: '#4BFFC8',
};
